---
deployment:
  tasks:
    - name: Deploy Website
      export GITREPO=https://github.com/digitalpartnersolutio/Tops-Payment.git
      export DEPLOYPATH=/home/n1571193/public_html/topsserver.com/
      /bin/rm -rf $DEPLOYPATH
      /bin/git clone $GITREPO $DEPLOYPATH
