---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - git clone https://github.com/<username>/<repository>.git $DEPLOYPATH
    - /bin/cp $DEPLOYPATH/<repository>/* $DEPLOYPATH
    - rm -rf $DEPLOYPATH/<repository>/